name: Build Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Mod
      uses: geode-sdk/build-geode-mod@main
      id: build
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: MultiplayerEdit-Windows
        path: ${{ steps.build.outputs.build-output }}

